[tool.poetry]
name = "examplelib"
version = "0.1.0"
description = ""
authors = ["Felix Qvist <felix.qvist@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
