VERSION 0.7
FROM gcr.io/dataflow-templates-base/python38-template-launcher-base
WORKDIR /pipeline

src-files:
  COPY pyproject.toml .
  COPY poetry.lock .

prepare:
  FROM +src-files
  RUN pip install poetry==1.4.2
  RUN poetry config virtualenvs.create false
  RUN poetry install --compile
  COPY src ./src


build:
  FROM +prepare
  ENV ENV=production
  ENV FLEX_TEMPLATE_PYTHON_PY_FILE="/pipeline/src/pipeline.py"
  ENV PIP_NO_DEPS=True
  ENTRYPOINT ["/opt/google/dataflow/python_template_launcher"]
  SAVE IMAGE --push europe-west1-docker.pkg.dev/tmrow-152415/pipelines/flex-test:latest

deploy:
  WAIT
    BUILD +build
  END
  FROM +build
  # We need poetry dependencies installed to deploy, so we manually install gsutil sdk here
  RUN curl -sSL https://sdk.cloud.google.com | bash

