VERSION 0.7
FROM apache/beam_python3.8_sdk:2.49.0
WORKDIR /pipeline

src-files:
  COPY ../examplelib+src-files/* /examplelib
  COPY pyproject.toml .
  COPY poetry.lock .

launcher-base:
    FROM gcr.io/dataflow-templates-base/flex-template-launcher-image
    SAVE ARTIFACT /opt/google/dataflow/python_template_launcher /launcher

prepare:
  FROM +src-files
  RUN pip install poetry==1.4.2
  RUN poetry config virtualenvs.create false
  RUN poetry install --compile
  COPY src ./src


build:
  FROM +prepare
  ENV ENV=production
  ENV FLEX_TEMPLATE_PYTHON_PY_FILE="/pipeline/src/pipeline.py"
  ENV PYTHONPATH="."
  COPY entry.sh /pipeline/entry.sh
  COPY +launcher-base/launcher /opt/google/dataflow/python_template_launcher
  ENTRYPOINT ["/pipeline/entry.sh"]
  SAVE IMAGE --push europe-west1-docker.pkg.dev/tmrow-152415/pipelines/flex-test:latest

build2:
    FROM +build
    ENTRYPOINT ["/opt/apache/beam/boot"]
    SAVE IMAGE --push europe-west1-docker.pkg.dev/tmrow-152415/pipelines/flex-test-worker:latest

deploy:
  WAIT
    BUILD +build
  END
  FROM +build
  # We need poetry dependencies installed to deploy, so we manually install gsutil sdk here
  RUN curl -sSL https://sdk.cloud.google.com | bash

